import { describe, it, expect } from 'vitest';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

const {
  qualityMultiplier,
  parseDiff,
  isAutoGenerated,
  normaliseMessage,
} = require('../main/commitAnalyser.js');

describe('qualityMultiplier', () => {
  const exts = n => new Set(Array.from({ length: n }, (_, i) => `.x${i}`));

  it('pure cleanup (deletions only) → 1.5', () => {
    expect(qualityMultiplier(0, 30, exts(1))).toBe(1.5);
  });

  it('mixed add+del across 2+ files → 1.5', () => {
    expect(qualityMultiplier(10, 10, exts(2))).toBe(1.5);
  });

  it('mixed add+del single file → 1.0', () => {
    expect(qualityMultiplier(10, 10, exts(1))).toBe(1.0);
  });

  it('additions only across 2+ files → 1.0', () => {
    expect(qualityMultiplier(20, 0, exts(2))).toBe(1.0);
  });

  it('additions only single file → 0.75', () => {
    expect(qualityMultiplier(20, 0, exts(1))).toBe(0.75);
  });
});

describe('isAutoGenerated', () => {
  it('flags merge commits', () => {
    expect(isAutoGenerated('Merge branch main into feature')).toBe(true);
    expect(isAutoGenerated('Merge pull request #42')).toBe(true);
  });

  it('flags wip / fixup / squash / version bumps', () => {
    expect(isAutoGenerated('WIP')).toBe(true);
    expect(isAutoGenerated('fixup! earlier commit')).toBe(true);
    expect(isAutoGenerated('squash! tidy')).toBe(true);
    expect(isAutoGenerated('bump version to 2.0')).toBe(true);
  });

  it('allows a normal message', () => {
    expect(isAutoGenerated('Add user authentication flow')).toBe(false);
  });
});

describe('normaliseMessage', () => {
  it('lowercases and collapses whitespace', () => {
    expect(normaliseMessage('  Fix   The   Bug  ')).toBe('fix the bug');
  });

  it('treats case/spacing variants as equal', () => {
    expect(normaliseMessage('Fix Bug')).toBe(normaliseMessage('fix   bug'));
  });
});

describe('parseDiff', () => {
  const diff = [
    '--- a/src/app.js',
    '+++ b/src/app.js',
    '+const a = 1;',
    '+const b = 2;',
    '-const old = 0;',
    '--- a/readme.md',
    '+++ b/readme.md',
    '+# Title',
  ].join('\n');

  it('counts additions and deletions, ignoring header lines', () => {
    const r = parseDiff(diff);
    expect(r.additions).toBe(3);
    expect(r.deletions).toBe(1);
  });

  it('collects distinct file extensions', () => {
    const r = parseDiff(diff);
    expect(r.fileExtensions.has('.js')).toBe(true);
    expect(r.fileExtensions.has('.md')).toBe(true);
  });

  it('ignores /dev/null paths', () => {
    const d = ['--- a/new.txt', '+++ b//dev/null', '-gone'].join('\n');
    const r = parseDiff(d);
    expect(r.deletions).toBe(1);
  });
});
