const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// ─── D-6: auto-generated commit message patterns ─────────────────────────────

const AUTO_GENERATED_PATTERNS = [
  'merge branch',
  'merge pull request',
  'auto-generated',
  'bump version',
  'update changelog',
  'wip',
  'fixup!',
  'squash!',
  'chore: release',
];

// ─── D-7: lockfile filenames ──────────────────────────────────────────────────

const LOCKFILES = new Set([
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'gemfile.lock',
  'poetry.lock',
  'cargo.lock',
  'composer.lock',
  'go.sum',
]);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function resolveGitBin() {
  if (process.platform !== 'win32') return 'git';
  const fallbacks = [
    'C:\\Program Files\\Git\\cmd\\git.exe',
    'C:\\Program Files (x86)\\Git\\cmd\\git.exe',
  ];
  for (const p of fallbacks) {
    if (fs.existsSync(p)) return `"${p}"`;
  }
  return 'git';
}

const GIT_BIN = resolveGitBin();

function runGit(args, cwd) {
  return execSync(`${GIT_BIN} ${args}`, {
    cwd,
    timeout: 5000,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  });
}

// D-6: returns true if the message matches any auto-generated pattern
function isAutoGenerated(message) {
  const lower = message.toLowerCase();
  return AUTO_GENERATED_PATTERNS.some(p => lower.includes(p));
}

// Normalise whitespace for D-3 comparison
function normaliseMessage(message) {
  return message.toLowerCase().replace(/\s+/g, ' ').trim();
}

// ─── D-5: diff quality multiplier ────────────────────────────────────────────

function qualityMultiplier(additions, deletions, fileExtensions) {
  const hasDeletions = deletions > 0;
  const hasAdditions = additions > 0;
  const fileCount = fileExtensions.size;

  if (!hasAdditions && hasDeletions) return 1.5;                       // pure cleanup
  if (hasDeletions && hasAdditions && fileCount >= 2) return 1.5;      // mixed, multi-file
  if (hasDeletions && hasAdditions && fileCount < 2) return 1.0;       // mixed, single-file
  if (!hasDeletions && hasAdditions && fileCount >= 2) return 1.0;     // additions only, multi-file
  return 0.75;                                                          // additions only, single-file
}

// ─── Diff parser ─────────────────────────────────────────────────────────────

function parseDiff(rawDiff) {
  let additions = 0;
  let deletions = 0;
  const fileExtensions = new Set();
  const fileNames = new Set();

  for (const line of rawDiff.split('\n')) {
    if (line.startsWith('+++ b/') || line.startsWith('--- a/')) {
      const filePath = line.slice(6).trim();
      if (filePath && filePath !== '/dev/null') {
        fileNames.add(path.basename(filePath).toLowerCase());
        const ext = path.extname(filePath);
        if (ext) fileExtensions.add(ext.toLowerCase());
      }
    } else if (line.startsWith('+') && !line.startsWith('+++')) {
      additions++;
    } else if (line.startsWith('-') && !line.startsWith('---')) {
      deletions++;
    }
  }

  return { additions, deletions, fileExtensions, fileNames };
}

// ─── D-1: discover commits in session window ─────────────────────────────────

function discoverCommits(repoPaths, startedAt, endedAt) {
  const afterIso = new Date(startedAt).toISOString();
  const beforeIso = new Date(endedAt).toISOString();
  const seen = new Set();
  // { hash, message, repoPath }
  const commits = [];

  for (const repoPath of repoPaths) {
    if (!fs.existsSync(path.join(repoPath, '.git'))) continue;
    try {
      const output = runGit(
        `log --after="${afterIso}" --before="${beforeIso}" --format="%H|%s" --all`,
        repoPath
      ).trim();

      if (!output) continue;

      for (const line of output.split('\n')) {
        const idx = line.indexOf('|');
        if (idx === -1) continue;
        const hash = line.slice(0, idx).trim();
        const message = line.slice(idx + 1).trim();
        if (!hash || seen.has(hash)) continue;  // D-1: deduplicate across repos
        seen.add(hash);
        commits.push({ hash, message, repoPath });
      }
    } catch (_) {
      // D-1: git log failure for this repo — skip, don't affect other repos
    }
  }

  // Return in chronological order (oldest first) for D-4 diminishing returns
  return commits.reverse();
}

// ─── D-2 + D-5 + D-7: analyse a single commit diff ──────────────────────────

function analyseDiff(hash, repoPath) {
  let rawDiff;
  try {
    rawDiff = runGit(`show ${hash} --format="" --unified=0`, repoPath);
  } catch (_) {
    // G-3: timeout or error — treat as disqualified
    return null;
  }

  const { additions, deletions, fileExtensions, fileNames } = parseDiff(rawDiff);
  const totalLines = additions + deletions;

  // D-2: fewer than 5 lines changed → disqualify
  if (totalLines < 5) return null;

  // D-7: all changed files are lockfiles → disqualify
  if (fileNames.size > 0 && [...fileNames].every(f => LOCKFILES.has(f))) return null;

  return { additions, deletions, fileExtensions, totalLines };
}

// ─── Main entry point ─────────────────────────────────────────────────────────

/**
 * Analyse all commits within a session window across the configured repos and
 * return a scored array of { xpAmount, reason } ready for awardSessionXp.
 *
 * @param {string[]} repoPaths - User-configured repo paths from settings.
 * @param {number}   startedAt - Session start timestamp (ms).
 * @param {number}   endedAt   - Session end timestamp (ms).
 * @returns {{ xpAmount: number, reason: string }[]}
 */
function analyseCommits(repoPaths, startedAt, endedAt) {
  if (!repoPaths || repoPaths.length === 0) return [];  // G-2

  const rawCommits = discoverCommits(repoPaths, startedAt, endedAt);
  if (rawCommits.length === 0) return [];

  // D-3: track normalised messages to detect duplicates within this session
  const seenMessages = new Map(); // normalisedMsg → first hash

  const scored = [];
  let qualifyingCount = 0;  // D-4: counts qualifying commits toward the 5-commit threshold

  for (const { hash, message, repoPath } of rawCommits) {
    // D-6: auto-generated message → disqualify
    if (isAutoGenerated(message)) continue;

    // D-3: duplicate message → disqualify all but first
    const normMsg = normaliseMessage(message);
    if (seenMessages.has(normMsg)) continue;
    seenMessages.set(normMsg, hash);

    // D-2 + D-5 + D-7: diff analysis
    const diff = analyseDiff(hash, repoPath);
    if (!diff) continue;  // disqualified by D-2 or D-7 (or git error)

    qualifyingCount++;

    // D-4: diminishing returns after 5 qualifying commits
    const baseXp = qualifyingCount <= 5 ? 5 : 2;

    // D-5: quality multiplier
    const mult = qualityMultiplier(diff.additions, diff.deletions, diff.fileExtensions);
    const rawXp = baseXp * mult;
    const xpAmount = Math.max(1, Math.floor(rawXp));  // D-5: minimum 1 XP

    scored.push({ hash, xpAmount, reason: `Commit ${hash.slice(0, 7)}: ${message.slice(0, 60)}` });
  }

  if (scored.length === 0) return [];

  // D-8: cap total commit bonus at 50 XP, scaling proportionally if needed
  const total = scored.reduce((sum, s) => sum + s.xpAmount, 0);
  if (total > 50) {
    const scale = 50 / total;
    return scored.map(s => ({
      xpAmount: Math.max(1, Math.floor(s.xpAmount * scale)),
      reason: s.reason,
    }));
  }

  return scored.map(({ xpAmount, reason }) => ({ xpAmount, reason }));
}

/**
 * Same qualification pipeline as analyseCommits but returns richer per-commit
 * data for badge evaluation (D-1: badges inherit XP qualification rules).
 *
 * @param {string[]} repoPaths
 * @param {number}   startedAt
 * @param {number}   endedAt
 * @returns {{
 *   hash: string,
 *   message: string,
 *   repoPath: string,
 *   additions: number,
 *   deletions: number,
 *   totalLines: number,
 *   fileExtensions: Set<string>,
 * }[]}
 */
function analyseCommitsRich(repoPaths, startedAt, endedAt) {
  if (!repoPaths || repoPaths.length === 0) return [];

  const rawCommits = discoverCommits(repoPaths, startedAt, endedAt);
  if (rawCommits.length === 0) return [];

  const seenMessages = new Map();
  const qualified = [];

  for (const { hash, message, repoPath } of rawCommits) {
    if (isAutoGenerated(message)) continue;
    const normMsg = normaliseMessage(message);
    if (seenMessages.has(normMsg)) continue;
    seenMessages.set(normMsg, hash);

    const diff = analyseDiff(hash, repoPath);
    if (!diff) continue;

    qualified.push({
      hash,
      message,
      repoPath,
      additions: diff.additions,
      deletions: diff.deletions,
      totalLines: diff.totalLines,
      fileExtensions: diff.fileExtensions,
    });
  }

  return qualified;
}

module.exports = { analyseCommits, analyseCommitsRich };
